col:
- tanggal
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
- max
- critical
- categori
dataset_dir: C:/Users/HP/Documents/Jeffri Ivander/Data Science/Pacmann AI academy/Tugas/ML
  Process/project/jeffri-zt9s_ML-_Process2/data/
datetime_columns:
- tanggal
int32_columns:
- pm10
- pm25
- so2
- co
- o3
- no2
- max
label: categori
label_categories:
- BAIK
- SEDANG
- TIDAK SEHAT
label_categories_new:
- BAIK
- TIDAK BAIK
missing_value_co: 11
missing_value_no2: 18
missing_value_o3: 29
missing_value_pm10:
  BAIK: 27
  TIDAK BAIK: 57
missing_value_pm25:
  BAIK: 38
  TIDAK BAIK: 84
missing_value_so2: 35
object_columns:
- stasiun
- critical
- categori
predictors:
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
range_co:
- -1
- 100
range_no2:
- -1
- 100
range_o3:
- -1
- 160
range_pm10:
- -1
- 800
range_pm25:
- -1
- 400
range_so2:
- -1
- 500
range_stasiun:
- DKI1 (Bunderan HI)
- DKI2 (Kelapa Gading)
- DKI3 (Jagakarsa)
- DKI4 (Lubang Buaya)
- DKI5 (Kebon Jeruk) Jakarta Barat
